# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

opt_out_usage

default_platform(:android)

platform :android do

  desc "Deploy appbundle to Google Play Internal Testing"
  lane :deploy do
    sh("git", "checkout", "master")
    sh("flutter", "build", "appbundle")

    # See http://docs.fastlane.tools/actions/upload_to_play_store/
    upload_to_play_store(
      # https://developers.google.com/android-publisher/tracks#ff-track-name
      track: "internal",
      #release_status: "draft",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      skip_upload_aab: false,
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      validate_only: false
    )
  end

end


platform :web do

  desc "Deploy to jithware.github.io/brethap"
  lane :deploy do
    sh("git", "checkout", "master")
    sh("flutter build web --base-href \"/brethap/\" --output docs/")
    sh("VER=$(grep \"version: \" ../pubspec.yaml) && cd .. && git add -A && git commit -m \"Web deploy $VER\" && git push")
  end

end