name: Flutter Tests

on:
  push:
    branches: [master, fdroid, release/v1, release/v2]
  pull_request:
    branches: [master, fdroid, release/v1, release/v2]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # See https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # See https://github.com/subosito/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
